substitutions:
  devicename: water-heater-bathroom
  upper_devicename: Bathroom Water Heater
  location: В ванной (в электо-бойлере)
  dallas_senson_sn: "0x000000000000"  # тут адрес вашего датчика
  manual_temperature: '80' #температура нагрева при ручном переключении
  wifi_ip: !secret ip_water_heater_bathroom

<<: !include -heater_basic_pzem_pattern.yaml
