substitutions:
  devicename: water-heater-bathroom
  upper_devicename: Bathroom Water Heater
  low_devicename: water_heater_bathroom
  location: В ванной (в электо-бойлере)     # тут место расположения на объекте
  dallas_senson_sn: "0x000000000"           # тут должен быть адрес термодатчика
  manual_temperature: '80'                  # температура нагрева при ручном переключении
  wifi_ip: !secret ip_water_heater_bathroom

<<: !include heater_basic_pzem_pattern.yaml
